building_name_generator/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index),
    path("generated-hash/", views.generateHash),
    path("view_map/", views.view_map),
    # urls for making multi dependent dropdown
    path('get_districts/', views.get_districts, name='get_districts'),
    path('get_municipalites/', views.get_municipalites, name='get_municipalites'),
]

navigator/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("building_name_generator.urls")),
]

building_name_generator/models.py
from django.db import models

# Create your models here.


class Province(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=2)

    def __str__(self):
        return self.name


class District(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=2)
    province = models.ForeignKey(Province, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Municipality(models.Model):
    type = models.CharField(max_length=2)
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=2)
    district = models.ForeignKey(District, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Wardnumber(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=2)
    municipality = models.ForeignKey(Municipality, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Road(models.Model):
    name = models.CharField(max_length=100)
    roadnumber = models.CharField(max_length=1)
    wardnumber = models.ForeignKey(Wardnumber, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Chowk(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=3)
    road = models.ForeignKey(Road, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.name


class HashedLocation(models.Model):
    province = models.ForeignKey(Province, on_delete=models.CASCADE)
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    municipality = models.ForeignKey(Municipality, on_delete=models.CASCADE)
    wardnumber = models.ForeignKey(Wardnumber, on_delete=models.CASCADE)
    road = models.ForeignKey(Road, on_delete=models.CASCADE)
    chowk = models.ForeignKey(Chowk, on_delete=models.CASCADE, null=True)
    locationnumber = models.CharField(max_length=100)
    locationoffset = models.CharField(max_length=100)
    locationType = models.CharField(max_length=100)

building_name_generator/forms.py
from django import forms
from building_name_generator.models import District, HashedLocation, Municipality


class GenerateHashForm(forms.ModelForm):
    district = forms.ModelChoiceField(queryset=District.objects.none())
    municipality = forms.ModelChoiceField(queryset=Municipality.objects.none())

    class Meta:
        model = HashedLocation
        fields = [
            'province',
            'district',
            'municipality',
            'wardnumber',
            'road',
            'chowk',
        ]

building_name_generator/views.py
import json
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render

from building_name_generator.models import Chowk, District, Municipality, Province, Road, Wardnumber
from .forms import GenerateHashForm
# Create your views here.


def index(request):
    if (request.method == 'POST'):
        form = GenerateHashForm(request.POST)
        print(form.data['province'])
        provinceCode = Province.objects.get(pk=form.data['province']).code
        districtCode = District.objects.get(pk=form.data['district']).code
        municipalityCode = Municipality.objects.get(
            pk=form.data['municipality']).code
        wardNumberCode = Wardnumber.objects.get(
            pk=form.data['wardnumber']).code
        roadCode = Road.objects.get(pk=form.data['road']).roadnumber
        chowkCode = Chowk.objects.get(pk=form.data['chowk']).code
        direction = form.data['direction']
        # calcualte midpoint
        midpoint = (int(form.data['start_distance']) +
                    int(form.data['end_distance'])) / 2
        # making it non floating
        midpoint = int(midpoint)
        if (form.data['side'] == 'R'):
            if (midpoint % 2 == 0):
                locationnumber = midpoint
            else:
                locationnumber = midpoint + 1
        else:
            if (midpoint % 2 != 0):
                locationnumber = midpoint
            else:
                locationnumber = midpoint + 1
        print(locationnumber)
        hashCode = f"{provinceCode}{districtCode}{municipalityCode}{wardNumberCode}{roadCode}{chowkCode}{direction}{locationnumber}"
        shortHashCode = f"{roadCode}{chowkCode}{direction}{locationnumber}"
        return render(request, "building_name_generator/generated-hash.html", {"hash": hashCode, "short_hash": shortHashCode, "details": {

        }})
    else:
        form = GenerateHashForm()
    return render(request, "building_name_generator/index.html", {"form": form})


def generateHash(request):
    return render(request, "building_name_generator/generated-hash.html", {"hash": "LuRdBu02EChaE36", "short_hash": "EChaE36"})


def view_map(request):
    mycoordinates = [
        {"name": "LuRuBu07KmcE199", "lat": 27.694401487589776, "lon": 83.47254691586639},
        {"name": "LuRuBu07BpcE370", "lat": 27.693595129709916, "lon": 83.47294560225534},
        {"name": "LuRuBu07MpcE79", "lat": 27.69407448603197, "lon": 83.47192580442817},
        {"name": "LuRuBu07MpcE149", "lat": 27.69356995428179, "lon": 83.47102311860016},
    ]
    coordinates_json = json.dumps(mycoordinates)
    return render(request, "building_name_generator/map.html", {'coordinates': coordinates_json})

# //getting data


def get_districts(request):
    province_id = request.GET.get('province_id')
    districts = District.objects.filter(province_id=province_id)
    data = [{'id': district.id, 'name': district.name}
            for district in districts]
    return JsonResponse({'districts': data})


def get_municipalites(request):
    district_id = request.GET.get('district_id')
    municipalities = Municipality.objects.filter(district_id=district_id)
    data = [{'id': municipality.id, 'name': municipality.name}
            for municipality in municipalities]
    return JsonResponse({'municipalities': data})

building_name_generator/templates/building_name_generator/generated-hash.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated Hash</title>
    <link
      rel="stylesheet"
      href="{% static 'building_name_generator/result.css'%}"
    />
  </head>
  <body>
    <div class="new-expense">
      <p class="short_hash">Short Hash: {{short_hash}}</p>
    </div>
    <div class="new-expense">
      <p class="short_hash">Long Hash: {{hash}}</p>
    </div>
  </body>
</html>

building_name_generator/templates/building_name_generator/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Building Name Generator</title>
    <link
      rel="stylesheet"
      href="{% static 'building_name_generator/style.css'%}"
    />
  </head>
  <body>
    <form action="" method="POST" class="new-expense">
      {% csrf_token %}
      <div class="new-expense__controls">
        {% for field in form %}
        <div
          class="expenses-filter__control expenses-filter {% if field.errors %}errors{% endif %}"
        >
          {{field.label_tag}} {{field}} {{field.errors}}
        </div>
        {% endfor %}
        <div class="expenses-filter__control expenses-filter">
          <label for="direction">Direction</label>
          <select name="direction" id="id_direction">
            <option value="E">East</option>
            <option value="W">West</option>
            <option value="N">North</option>
            <option value="S">South</option>
          </select>
        </div>
      </div>

      <div class="new-expense__controls">
        <div class="new-expense__control">
          <label for="start_distance">Start Distance</label>
          <input type="text" name="start_distance" />
        </div>
        <div class="new-expense__control">
          <label for="end_distance">End Distance</label>
          <input type="text" name="end_distance" />
        </div>
        <div class="new-expense__control">
          <label for="side">Side</label>
          <input type="text" name="side" />
        </div>
      </div>

      <button type="submit">Send</button>
    </form>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
      $(document).ready(function () {
        $("#id_province").change(function () {
          var provinceId = $(this).val();
          $.ajax({
            url: '{% url "get_districts" %}',
            data: { province_id: provinceId },
            dataType: "json",
            success: function (data) {
              var districtSelect = $("#id_district");
              districtSelect.empty();
              districtSelect.append(
                $("<option>", {
                  value: "",
                  text: "Select District",
                })
              );
              $.each(data.districts, function (index, district) {
                districtSelect.append(
                  $("<option>", {
                    value: district.id,
                    text: district.name,
                  })
                );
              });
            },
          });
        });
        $("#id_district").change(function () {
          var districtId = $(this).val();
          $.ajax({
            url: '{% url "get_municipalites" %}',
            data: { district_id: districtId },
            dataType: "json",
            success: function (data) {
              var municipalitySelect = $("#id_municipality");
              municipalitySelect.empty();
              municipalitySelect.append(
                $("<option>", {
                  value: "",
                  text: "Select Municipality",
                })
              );
              $.each(data.municipalities, function (index, municipality) {
                municipalitySelect.append(
                  $("<option>", {
                    value: municipality.id,
                    text: municipality.name,
                  })
                );
              });
            },
          });
        });
      });
    </script>
  </body>
</html>

building_name_generator/templates/building_name_generator/map.html
<!DOCTYPE html>
<html>
  <head>
    <title>Map</title>
    <link
      rel="stylesheet"
      href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
    />
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
  </head>
  <body>
    <div id="map" style="width: 100%; height: 500px"></div>

    <script>
      var map = L.map("map").setView([27.7, 85.3], 8);

      L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
        attribution:
          '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
      }).addTo(map);

      var coordinates = JSON.parse("{{ coordinates | escapejs }}");
      for (var i = 0; i < coordinates.length; i++) {
        L.marker([coordinates[i].lat, coordinates[i].lon])
          .addTo(map)
          .bindPopup(coordinates[i].name);
      }
    </script>
  </body>
</html>